name: Pipeline CI/CD DataOps

on:
  push:
    branches:
      - feature/esteira

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: pip install flake8
      - run: flake8 --max-line-length=120 app tests

      - run: pip install pytest
      - run: pytest